name: Update Surge rules

on:
  push:
    branches: [master]
    paths:
      - 'Prototype.conf'
      - '.github/**'
  schedule:
    - cron: 0 * * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone repository
        run: git clone https://github.com/fgprodigal/Surge-Rule.git Surge-Rule

      - name: Get rules and modules
        run: |
          mkdir -p Surge-Rule/Rules
          mkdir -p Surge-Rule/Module
          mkdir -p Surge-Rule/Script
          curl -o Surge-Rule/Rules/apple.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt
          curl -o Surge-Rule/Rules/icloud.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/icloud.txt
          curl -o Surge-Rule/Rules/google.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/google.txt
          curl -o Surge-Rule/Rules/proxy.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt
          curl -o Surge-Rule/Rules/direct.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt
          curl -o Surge-Rule/Rules/cncidr.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt
          curl -o Surge-Rule/Rules/netflix.list https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Media/Netflix.list
          curl -o Surge-Rule/Rules/cn-ad.list https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/Rulesets/Surge/Custom/CN-ad.list

          curl -o Surge-Rule/Module/douyin.sgmodule https://raw.githubusercontent.com/Choler/Surge/master/Module/douyin.sgmodule
          sed -i 's#https://Choler.github.io/Surge#https://cdn.jsdelivr.net/gh/fgprodigal/Surge-Rule@master#g' Surge-Rule/Module/douyin.sgmodule
          curl -o Surge-Rule/Script/douyin.js https://raw.githubusercontent.com/Choler/Surge/master/Script/douyin.js

          git clone https://github.com/yichahucha/surge.git -b master yichahucha
          sed -i 's#https://raw.githubusercontent.com/yichahucha/surge/master#https://cdn.jsdelivr.net/gh/fgprodigal/Surge-Rule@master/Script#g' Surge-Rule/Module/*.sgmodule
          cp yichahucha/*.js Surge-Rule/Script/

          # git clone https://github.com/onewayticket255/Surge-Script.git onewayticket255
          # cp onewayticket255/module/*.sgmodule Surge-Rule/Module/
          sed -i 's#https://raw.githubusercontent.com/onewayticket255/Surge-Script/master#https://cdn.jsdelivr.net/gh/fgprodigal/Surge-Rule@master/Script#g' Surge-Rule/Module/*.sgmodule
          cp onewayticket255/*.js Surge-Rule/Script/

      - name: URL Rewrite
        run: |
          cd Surge-Rule
          cp -f Prototype.conf Ray.conf

          sed -i '/# URL Rewrite/{
            r Rules/url_rewrite.txt
            /# URL Rewrite/d
          }' Ray.conf

          sed -i '/# Hostname/{
            r Rules/hostname.txt
            /# Hostname/d
          }' Ray.conf

          sed -i '/# Script/{
            r Rules/script.txt
            /# Script/d
          }' Ray.conf

      - name: Git commit
        id: commit
        run: |
          cd Surge-Rule
          git config --local user.email "769910+fgprodigal@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git add -A
          if ! git diff-index --quiet --cached HEAD; then
            git commit -am "Auto updated at $(date)"
            echo "::set-output name=changes::true"
          fi
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        if: steps.commit.outputs.changes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          directory: 'Surge-Rule'

      - name: Purge jsDelivr
        if: steps.commit.outputs.changes
        run: |
          curl https://purge.jsdelivr.net/gh/fgprodigal/Surge-Rule@master/Ray.conf
